# ============================================================

# DEVELOPMENT DATABASE - LOCAL SQL SERVER

# ============================================================

spring.datasource.url=jdbc:sqlserver://localhost:1433;Database=springBoot;Trusted_Connection=True;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Cnn@91%,

# ============================================================

# SERVER

# ============================================================

server.port=8888

# ============================================================

# SPRING SECURITY

# ============================================================

spring.security.user.name=chandranBE
spring.security.user.password=Cnn@91%,

# ============================================================

# EMAIL

# ============================================================

spring.mail.username=YOUR_MAIL_USERNAME
spring.mail.password=YOUR_MAIL_PASSWORD
