#  DB PROPERTIES
#------------------
spring.datasource.url= jdbc:sqlserver://localhost:1433;Database=springBoot;Trusted_Connection=True;encrypt=true;trustServerCertificate=true;
spring.datasource.username= sa
spring.datasource.password= Cnn@91%,

# HIBERNATE AND JPA PROPERTIES
#------------------------------
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto = update

!--------------------solution for database update ------------------------------------------------------!
#spring.datasource.url=jdbc:h2:file:./data/demo
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
#spring.datasource.platform=h2
#!-----------Sorry, remote connections ('webAllowOthers') are disabled on this server.--------------------!
#spring.h2.console.settings.web-allow-others=true
!--------------------------------------
spring.port=9090
spring.security.user.name = chandranBE
spring.security.user.password =Cnn@91%,

!------------------Run a project with ip address---------------------------------------------------------!
#server.address=192.168.5.216
server.port=8888
!------------------Run a project with ip address---------------------------------------------------------!
!--------------------------------------------------------------------------------!
spring.jpa.defer-datasource-initialization=true

#---------------------------------email properties---------start----------------------------------------->
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=username
spring.mail.password=password

#---------------------------MAIL  Other properties START ------------------------------------------------>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true

#----------------------------------email properties---------end------------------------------------------>

#----------------------------multipart file size setting-------------------------------------------->
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

#******************************************************************************************************>
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl