# ============================================================

# PRODUCTION DATABASE - AZURE SQL

# ============================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ============================================================

# SERVER - RENDER

# ============================================================

server.address=0.0.0.0
server.port=${PORT:8888}

# ============================================================

# SPRING SECURITY

# ============================================================

spring.security.user.name=${SECURITY_USERNAME:chandranBE}
spring.security.user.password=${SECURITY_PASSWORD}

# ============================================================

# EMAIL

# ============================================================

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
